### ISSUE TITLE
Cannot read property '1' of null

### ISSUE THREAD

**Issue by juniorclearmetal** [cavhoo/react-project-graph#2]
This is a great concept! When I try to run it I get the following:

```
$ node index.js -p /Users/username/dev/web/src/
TypeError: Cannot read property '1' of null
    at parseFileImports (/Users/username/dev/react-project-graph/index.js:24:32)
    at ComponentFile.getImports (/Users/username/dev/react-project-graph/index.js:40:25)
    at new ComponentFile (/Users/username/dev/react-project-graph/index.js:36:14)
    at main (/Users/username/dev/react-project-graph/index.js:134:21)
    at Object.<anonymous> (/Users/username/dev/react-project-graph/index.js:153:1)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
```

**Comment by jfelipebc** [comment]
Hi @juniorclearmetal you can replace parseFileImports for this
```  const importmap = [];
  const filecontent = fs.readFileSync(file);

  const filecontentlines = filecontent.toString().split(/\r|\n/g);
  for (var i = 0, l = filecontentlines.length; i < l; i++) {
    const line = filecontentlines[i];
    if (line.match(/^(import).+(from|require)/)) {
      const impClass = importRegEx.exec(line);
      const impFrom = importPathRegEx.exec(line);
      if (impClass !== null) {
        importmap[impClass[1].trim()] = impFrom[2];
      }
    }
  }
  return importmap;
};```and works.

**Comment by jfelipebc** [comment]
Hi @juniorclearmetal 
Replace this parseFileImports with this code, and works
```const parseFileImports = file => {
  const importmap = [];
  const filecontent = fs.readFileSync(file);

  const filecontentlines = filecontent.toString().split(/\r|\n/g);
  for (var i = 0, l = filecontentlines.length; i < l; i++) {
    const line = filecontentlines[i];
    if (line.match(/^(import).+(from|require)/)) {
      const impClass = importRegEx.exec(line);
      const impFrom = importPathRegEx.exec(line);
      if (impClass !== null) {
        importmap[impClass[1].trim()] = impFrom[2];
      }
    }
  }
  return importmap;
};

**Comment by cavhoo** [comment]
Hey sorry for inactivity, had some family stuff that came up right afterwards and I was only focusing on work and that.

Right now I am fine tuning the RegExes to be more robust when parsing imports from files, in the branch Version2. 

The fix @jfelipebc suggested should work though.
